music/history/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('add/', views.ArtistFormView.as_view(), name='artist_form'),
    path('<int:artist_id>/', views.artist, name='artist'),
    
    path('<int:artist_id>/album/<int:album_id>/', views.song_view, name='album')
    
    # ex: /polls/5/results/
    # path('<int:artist_id>/song/', views.songs, name='songs'),
]

music/music/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('history/', include('history.urls')),
]

music/history/models.py
from django.db import models


class Artist(models.Model):
    artist_name = models.CharField(max_length=200)
    est_date = models.IntegerField('date established')
    def __str__(self):
        return self.artist_name


class Song(models.Model):
    album = models.ForeignKey('Album', on_delete=models.CASCADE)
    artist = models.ForeignKey('Artist', on_delete=models.CASCADE)
    song_title = models.CharField(max_length=200)
    song_length = models.IntegerField(default=0)
    def __str__(self):
        return self.song_text

class Album(models.Model):
    artist = models.ForeignKey('Artist', on_delete=models.CASCADE)
    album_name = models.CharField(max_length=200)
    album_length = models.IntegerField(default=0)
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE)
    def __str__(self):
        return self.album_name

class Genre(models.Model):
    genre_name = models.CharField(max_length=200)
    def __str__(self):
        return self.genre_name

music/history/forms.py
from django import forms
from .models import Artist

class ArtistForm(forms.ModelForm):

  class Meta:
      model = Artist
      fields = ('artist_name', 'est_date')

music/history/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.views.generic import ListView, TemplateView, FormView, DetailView, CreateView

from .models import Artist, Album
from .forms import ArtistForm


def index(request):
    artist_list = Artist.objects.order_by('-est_date')[:5]
    context = {'artist_list': artist_list}
    return render(request, 'history/index.html', context)

    def return_artist_form(self):
        return ArtistFormView

# gets the details of artist including their song
def artist(request, artist_id):
    print(artist_id)
    try:
        artist = Artist.objects.get(pk=artist_id)
    except Artist.DoesNotExist:
        raise Http404("Artist does not exist")
    return render(request, 'history/songs.html', {'artist': artist})

def song_view(request, artist_id, album_id):
    print(album_id)
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album Detail does not exist")
    return render(request, 'history/collection_list.html', {'album': album})


class ArtistFormView(FormView):
  template_name = 'history/artist_form.html'
  form_class = ArtistForm
  # NOTE! Be sure to put the slash in front of the url to route properly
  success_url = '/history/'

  def form_valid(self, form):
    # This method is called when valid form data has been POSTed.
    # It should return an HttpResponse.
    form.save()
    return super(ArtistFormView, self).form_valid(form)
  
  

music/history/templates/history/artist_form.html
<h3>Add a new artist to your collection</h3>

<form method='post'>
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Save Artist">
</form>

music/history/templates/history/collection_list.html
{% extends "history/index.html"%}

{% block content %}


<h1>{{ artist.artist_name }}</h1>
<h2>Song List</h2>
<!-- <h2>{{view.message.header|upper}}</h2> -->
<ul>
    {% for album in album.song_set.all %}
    <li>{{ album.song_title }}</li>
    {% endfor %}
</ul>
    {% endblock %}

music/history/templates/history/index.html
{% load static %}

<link href="https://fonts.googleapis.com/css?family=Knewave|Roboto+Condensed" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'history/style.css' %}" />

<h2>Music History </h2>

{% block content %}

{% if artist_list %}
    <ul>
    {% for artist in artist_list %}
        <li><a href="/history/{{ artist.id }}/">{{ artist.artist_name }}</a></li>
    {% endfor %}
    </ul>
    
    <h3>Add a new artist to your collection</h3>

    <form method='post'>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Save Artist">
    </form>

{% else %}
    <p>No artists are available.</p>
{% endif %}

{% endblock%}

music/history/templates/history/songs.html
{% extends "history/index.html" %}

{% block content %}


<h1>{{ artist.artist_name }}</h1>
<h3>Albums</h3>

<ul>
    {% for album in artist.album_set.all %}
    <!-- <li>{{ album.album_name }}</li> -->
    <li><a href="album/{{ album.id }}/">{{ album.album_name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}